apiVersion: apps/v1 
kind: Deployment 
metadata: 
 name: jenkins-docker-hub 
spec: 
 replicas: 2
 strategy: 
  type: RollingUpdate 
 selector: 
  matchLabels: 
   app: jenkins-docker-hub 
 template: 
   metadata: 
    labels: 
     app: jenkins-docker-hub
     env: prod 
   spec: 
    containers: 
    - name: jenkins-docker-hub 
      image: chaimakh/jenkins-docker-hub:latest
      ports:
      - containerPort: 4200
      command: ["ng","serve","--host","0.0.0.0","--port","4200"]
      env:
      - name: URL
        value: "http://10.100.119.179:32221"
