apiVersion: v1
kind: Service
metadata:
 name: jenkins-docker-hub
spec:
 type: NodePort
 selector:
   app: jenkins-docker-hub
   env: prod
 ports:
 - name: test
   protocol: TCP
   port: 80
   targetPort: 4200
   nodePort: 32222
